# 🧠 SPARK Academy 2026 — Week 2 Quiz

### Python Basics & Introduction to NumPy

**Rules:**
- Look at the code
- **1 minute** to think
- Shout your answer!
- I run the cell to reveal the answer

---
**Let's go! 🚀**


---
## ❓ Question 1 — List Comprehension

In [1]:
tumors = [1.2, 3.5, 0.8, 4.1, 2.9]
sizes_mm = [t * 10 for t in tumors]
print(sizes_mm)

[12.0, 35.0, 8.0, 41.0, 29.0]


---
## ❓ Question 2 — List Comprehension + Filter

In [2]:
tumors = [1.2, 3.5, 0.8, 4.1, 2.9]
critical = [t for t in tumors if t > 3.0]
print(critical)

[3.5, 4.1]


---
## ❓ Question 3 — if/elif/else

In [3]:
age = 70
tumor_cm = 2.5

if tumor_cm > 3.0 and age > 65:
    print("HIGH priority")
elif tumor_cm > 3.0:
    print("MEDIUM priority")
elif age > 65:
    print("MONITOR closely")
else:
    print("ROUTINE")

MONITOR closely


---
## ❓ Question 4 — enumerate()

In [4]:
scans = ["MRI", "CT", "X-Ray"]
for i, scan in enumerate(scans):
    print(f"Scan {i}: {scan}")

Scan 0: MRI
Scan 1: CT
Scan 2: X-Ray


---
## ❓ Question 5 — while Loop

In [5]:
dose = 10
steps = 0
while dose < 40:
    dose += 15
    steps += 1
print(f"Final dose: {dose}, Steps: {steps}")

Final dose: 40, Steps: 2


---
## ❓ Question 6 — Functions

In [6]:
def classify(size):
    if size > 3.0:
        return "Critical"
    else:
        return "Stable"

print(classify(4.2))
print(classify(1.5))

Critical
Stable


---
## ❓ Question 7 — Default Parameters

In [7]:
def greet(name, dept="Radiology"):
    return f"{name} - {dept}"

print(greet("Amina"))
print(greet("Kofi", "Oncology"))

Amina - Radiology
Kofi - Oncology


---
## ❓ Question 8 — NumPy Arrays

In [8]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a * 2)
print(a + 5)

[ 20  40  60  80 100]
[15 25 35 45 55]


---
## ❓ Question 9 — NumPy Functions

In [9]:
import numpy as np

pixels = np.array([50, 180, 30, 220, 90])
print(np.max(pixels))
print(np.min(pixels))
print(np.mean(pixels))

220
30
114.0


---
## ❓ Question 10 — Boolean Indexing

In [10]:
import numpy as np

pixels = np.array([50, 180, 30, 220, 90])
bright = pixels[pixels > 100]
print(bright)
print(len(bright))

[180 220]
2


---
## ❓ Question 11 — Array Slicing

In [11]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60])
print(data[1:4])
print(data[::2])

[20 30 40]
[10 30 50]


---
## ❓ Question 12 — 2D Array Indexing

In [12]:
import numpy as np

image = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(image[0, 2])
print(image[2, 0])
print(image[1, :])

30
70
[40 50 60]


---
## ❓ Question 13 — 2D Slicing

In [13]:
import numpy as np

image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90,100,110,120]
])
roi = image[0:2, 1:3]
print(roi)
print(roi.shape)

[[20 30]
 [60 70]]
(2, 2)


---
## ❓ Question 14 — Function + NumPy

In [14]:
import numpy as np

def calculate_snr(signal, background):
    return np.mean(signal) / np.std(background)

signal = np.array([200, 210, 190])
bg = np.array([10, 12, 8])
print(f"SNR: {calculate_snr(signal, bg):.1f}")

SNR: 122.5


---
## ❓ Question 15 — The Big One 🏆

In [15]:
import numpy as np

tumors = np.array([1.2, 3.5, 0.8, 4.1, 2.9])

critical = tumors[tumors > 3.0]
names = ["Fatima", "Chidi", "Amina", "Bola", "Kofi"]
crit_names = [n for n, t in zip(names, tumors) if t > 3.0]

print(f"Critical tumors: {critical}")
print(f"Patients: {crit_names}")
print(f"Average critical size: {np.mean(critical):.1f} cm")

Critical tumors: [3.5 4.1]
Patients: ['Chidi', 'Bola']
Average critical size: 3.8 cm


---

# 🎉 Quiz Complete!

### Great job! You've covered:
- List comprehensions
- Control structures (if/elif/else, loops)
- Functions
- NumPy arrays, operations, slicing, 2D indexing
- SNR calculation

**SPARK Academy 2026 — Train for Change, From Science to Practice** 🚀
